/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Modified: added orbiting animation from Threlte example
*/

import * as THREE from "three";
import React, { useMemo, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: Record<string, THREE.Mesh>;
  materials: Record<string, THREE.MeshStandardMaterial>;
};

const orbitConfig = {
  pepe: {
    radius: 5,
    speed: 0.8,
    angle: 0,
    axis: new THREE.Vector3(0.2, 1, 0.3).normalize(),
  },
  pinguin: {
    radius: 3,
    speed: 0.6,
    angle: Math.PI / 2,
    axis: new THREE.Vector3(-0.5, 0.7, 0.1).normalize(),
  },
  doge: {
    radius: 0,
    speed: 1.0,
    angle: Math.PI,
    axis: new THREE.Vector3(0.1, -0.8, 0.4).normalize(),
  },
  cat: {
    radius: 3,
    speed: 0.7,
    angle: (3 * Math.PI) / 2,
    axis: new THREE.Vector3(0.6, 0.2, -0.5).normalize(),
  },
  shiba: {
    radius: 3,
    speed: 0.5,
    angle: Math.PI / 4,
    axis: new THREE.Vector3(-0.3, 0.9, -0.2).normalize(),
  },
  near: {
    radius: 4,
    speed: 0.9,
    angle: (3 * Math.PI) / 4,
    axis: new THREE.Vector3(0.4, -0.1, 0.7).normalize(),
  },
  electrum: {
    radius: 5,
    speed: 0.8,
    angle: (5 * Math.PI) / 4,
    axis: new THREE.Vector3(-0.2, -0.6, 0.5).normalize(),
  },
};

const lineVertexShader = `
  varying vec2 vUv;
  void main() {
    vUv = uv;
    gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
  }
`;

const lineFragmentShader = `
  uniform vec3 color;
  uniform float dashArray;
  uniform float dashRatio;
  uniform float dashOffset;
  uniform float opacity;
  varying vec2 vUv;

  void main() {
    float pattern = fract(vUv.x * dashArray - dashOffset);
    if (pattern > dashRatio) discard;
    gl_FragColor = vec4(color, opacity);
  }
`;

export function Model({
  opacityRef,
  ...props
}: {
  opacityRef?: React.RefObject<number>;
} & React.JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/coins.glb") as unknown as GLTFResult;

  const lastOpacity = useRef(1);
  const dashOffsetRef = useRef(0);
  const colorProgressRef = useRef(0);
  const lineMaterialRef = useRef<THREE.ShaderMaterial>(null);

  const catRef = useRef<THREE.Group>(null);
  const shibaRef = useRef<THREE.Group>(null);
  const pepeRef = useRef<THREE.Group>(null);
  const dogeRef = useRef<THREE.Group>(null);
  const pinguinRef = useRef<THREE.Group>(null);
const nearRef = useRef<THREE.Group>(null);
const electrumRef = useRef<THREE.Group>(null);
const nearCoinMaterialRef = useRef<THREE.MeshStandardMaterial>(null);

  const orange = useMemo(() => new THREE.Color("#fe3d00"), []);
  const purple = useMemo(() => new THREE.Color("#9800fe"), []);
  const colorTemp = useMemo(() => new THREE.Color(), []);

  const lineUniforms = useMemo(
    () => ({
      color: { value: new THREE.Color("#fe3d00") },
      dashArray: { value: 0.5 },
      dashRatio: { value: 0.5 },
      dashOffset: { value: 0.0 },
      opacity: { value: 1.0 },
    }),
    [],
  );

  useFrame((_, delta) => {
    const opacity = opacityRef?.current ?? 1;

    // Update materials opacity
    if (opacity !== lastOpacity.current) {
      lastOpacity.current = opacity;
      Object.values(materials).forEach((m: any) => {
        m.transparent = opacity < 1;
        m.opacity = opacity;
        m.needsUpdate = true;
      });
      lineUniforms.opacity.value = opacity;
if (lineMaterialRef.current) {
  lineMaterialRef.current.uniforms.opacity.value = opacity;
  lineMaterialRef.current.needsUpdate = true;
}
if (nearCoinMaterialRef.current) {
  nearCoinMaterialRef.current.transparent = opacity < 1;
  nearCoinMaterialRef.current.opacity = opacity;
  nearCoinMaterialRef.current.needsUpdate = true;
}
    }

    // Orbit animation
    const configs = [
      { ref: catRef, config: orbitConfig.cat },
      { ref: shibaRef, config: orbitConfig.shiba },
      { ref: pepeRef, config: orbitConfig.pepe },
      { ref: dogeRef, config: orbitConfig.doge },
      { ref: pinguinRef, config: orbitConfig.pinguin },
      { ref: nearRef, config: orbitConfig.near },
      { ref: electrumRef, config: orbitConfig.electrum },
    ];

    configs.forEach(({ ref, config }) => {
      if (!ref.current) return;
      config.angle += delta * config.speed;

      const newPosition = new THREE.Vector3()
        .set(1, 0, 0)
        .applyAxisAngle(config.axis, config.angle)
        .multiplyScalar(config.radius);

      ref.current.position.copy(newPosition);
      ref.current.rotation.y += delta * config.speed * 0.5;
      ref.current.rotation.x += delta * config.speed * 0.3;
    });

    // Line animation
    dashOffsetRef.current += delta / 2;
    colorProgressRef.current = (colorProgressRef.current + delta * 0.1) % 1;

    lineUniforms.dashOffset.value = dashOffsetRef.current;
    lineUniforms.color.value.copy(
      colorTemp.lerpColors(orange, purple, colorProgressRef.current),
    );
  });

  return (
    <group {...props} dispose={null} scale={0.9}>
      <group position={[2, 0, 0]} scale={0.3}>
        <group ref={catRef} name="cat" scale={0.5} position={[-0.01, 0, 0]}>
          <mesh
            geometry={nodes.cat_1.geometry}
            material={materials["Material.020"]}
          />
          <mesh
            geometry={nodes.cat_2.geometry}
            material={materials["SVGMat.012"]}
          />
          <mesh
            geometry={nodes.cat_3.geometry}
            material={materials["Material.019"]}
          />
          <mesh
            geometry={nodes.cat_4.geometry}
            material={materials["Material.023"]}
          />
          <mesh
            geometry={nodes.cat_5.geometry}
            material={materials["Material.025"]}
          />
          <mesh
            geometry={nodes.cat_6.geometry}
            material={materials["Material.026"]}
          />
          <mesh
            geometry={nodes.cat_7.geometry}
            material={materials["Material.022"]}
          />
          <mesh
            geometry={nodes.cat_8.geometry}
            material={materials["Material.021"]}
          />
          <mesh
            geometry={nodes.cat_9.geometry}
            material={materials["Material.031"]}
          />
          <mesh
            geometry={nodes.cat_10.geometry}
            material={materials["Near Logo"]}
          />
          <mesh
            geometry={nodes.cat_11.geometry}
            material={materials["Material.028"]}
          />
          <mesh
            geometry={nodes.cat_12.geometry}
            material={materials["Material.032"]}
          />
          <mesh
            geometry={nodes.cat_13.geometry}
            material={materials["Material.030"]}
          />
          <mesh
            geometry={nodes.cat_14.geometry}
            material={materials["Material.027"]}
          />
          <mesh
            geometry={nodes.cat_15.geometry}
            material={materials["Material.024"]}
          />
          <mesh
            geometry={nodes.cat_16.geometry}
            material={materials["Material.007"]}
          />
        </group>
        <group ref={shibaRef} name="shiba" scale={0.5} position={[0, 0.01, 0]}>
          <mesh
            geometry={nodes.shiba_1.geometry}
            material={materials["Shiba logo 1"]}
          />
          <mesh
            geometry={nodes.shiba_2.geometry}
            material={materials["Shiba logo 4"]}
          />
          <mesh
            geometry={nodes.shiba_3.geometry}
            material={materials["Material.030"]}
          />
          <mesh
            geometry={nodes.shiba_4.geometry}
            material={materials["Near Logo"]}
          />
          <mesh
            geometry={nodes.shiba_5.geometry}
            material={materials["Shiba inu Coin"]}
          />
        </group>
        <group
          ref={pepeRef}
          name="pepe"
          scale={0.5}
          position={[-0.01, -0.01, 0]}
        >
          <mesh
            geometry={nodes.pepe_1.geometry}
            material={materials["SVGMat.012"]}
          />
          <mesh geometry={nodes.pepe_2.geometry} material={materials.SVGMat} />
          <mesh
            geometry={nodes.pepe_3.geometry}
            material={materials["SVGMat.001"]}
          />
          <mesh
            geometry={nodes.pepe_4.geometry}
            material={materials["Pepe Coin"]}
          />
        </group>
        <group ref={nearRef} name="near" scale={0.5}>
          <mesh
            geometry={nodes.near001.geometry}
            rotation={[0, 0, -Math.PI]}
            scale={[1.02, 1.02, 1.03]}
          >
            <meshStandardMaterial ref={nearCoinMaterialRef} color="black" />
          </mesh>

          <mesh
            geometry={nodes.Curve001.geometry}
            rotation={[Math.PI / 2, 0, 0]}
            scale={38.939}
          >
            <shaderMaterial
              ref={lineMaterialRef}
              vertexShader={lineVertexShader}
              fragmentShader={lineFragmentShader}
              uniforms={lineUniforms}
              transparent
              depthTest={true}
              depthWrite={false}
              side={THREE.DoubleSide}
            />
          </mesh>
        </group>
        <group ref={electrumRef} name="electrum" scale={0.5}>
          <mesh
            geometry={nodes.electrum_1.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            geometry={nodes.electrum_2.geometry}
            material={materials["SVGMat.006"]}
          />
          <mesh
            geometry={nodes.electrum_3.geometry}
            material={materials["SVGMat.008"]}
          />
        </group>
        <group ref={dogeRef} name="doge">
          <mesh
            geometry={nodes.doge_1.geometry}
            material={materials["Near Logo"]}
          />
          <mesh
            geometry={nodes.doge_2.geometry}
            material={materials["Material.066"]}
          />
          <mesh
            geometry={nodes.doge_3.geometry}
            material={materials["Material.061"]}
          />
          <mesh
            geometry={nodes.doge_4.geometry}
            material={materials["Material.064"]}
          />
          <mesh
            geometry={nodes.doge_5.geometry}
            material={materials["Material.062"]}
          />
          <mesh
            geometry={nodes.doge_6.geometry}
            material={materials["Material.067"]}
          />
          <mesh
            geometry={nodes.doge_7.geometry}
            material={materials["Material.063"]}
          />
          <mesh
            geometry={nodes.doge_8.geometry}
            material={materials["Material.065"]}
          />
          <mesh
            geometry={nodes.doge_9.geometry}
            material={materials["Material.069"]}
          />
          <mesh
            geometry={nodes.doge_10.geometry}
            material={materials["Material.068"]}
          />
          <mesh
            geometry={nodes.doge_11.geometry}
            material={materials["Material.070"]}
          />
          <mesh
            geometry={nodes.doge_12.geometry}
            material={materials["Material.071"]}
          />
          <mesh
            geometry={nodes.doge_13.geometry}
            material={materials["Material.073"]}
          />
        </group>
        <group ref={pinguinRef} name="pinguin" scale={0.5}>
          <mesh
            geometry={nodes.pinguin001.geometry}
            material={materials["Material.013"]}
          />
          <mesh
            geometry={nodes.pinguin001_1.geometry}
            material={materials["default.003"]}
          />
          <mesh
            geometry={nodes.pinguin001_2.geometry}
            material={materials["Material.033"]}
          />
          <mesh
            geometry={nodes.pinguin001_3.geometry}
            material={materials["Material.034"]}
          />
          <mesh
            geometry={nodes.pinguin001_4.geometry}
            material={materials["Material.035"]}
          />
          <mesh
            geometry={nodes.pinguin001_5.geometry}
            material={materials["Material.070"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/coins.glb");
