<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 ./coin.glb -T
-->

<script>
  import { Group } from 'three'

  import { T } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  ref = new Group()

  const gltf = useGltf('/coin-transformed.glb')

  export const { actions, mixer } = useGltfAnimations(gltf, ref)
</script>

<T
  is={ref}
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="Scene">
      <T.Group
        name="Curve002"
        rotation={[Math.PI / 2, 0, 0]}
        scale={370.82}
      >
        <T.Mesh
          name="Curve091"
          geometry={gltf.nodes.Curve091.geometry}
          material={gltf.materials.SVGMat}
        />
        <T.Mesh
          name="Curve091_1"
          geometry={gltf.nodes.Curve091_1.geometry}
          material={gltf.materials['Pepe Coin']}
        />
        <T.Mesh
          name="Curve091_2"
          geometry={gltf.nodes.Curve091_2.geometry}
          material={gltf.materials['SVGMat.001']}
        />
        <T.Mesh
          name="Curve091_3"
          geometry={gltf.nodes.Curve091_3.geometry}
          material={gltf.materials['SVGMat.002']}
        />
      </T.Group>
      <T.Group
        name="Cylinder001"
        rotation={[Math.PI / 2, 0, 0]}
      >
        <T.Mesh
          name="Cylinder001_1"
          geometry={gltf.nodes.Cylinder001_1.geometry}
          material={gltf.materials['Material.014']}
        />
        <T.Mesh
          name="Cylinder001_2"
          geometry={gltf.nodes.Cylinder001_2.geometry}
          material={gltf.materials['Material.016']}
        />
        <T.Mesh
          name="Cylinder001_3"
          geometry={gltf.nodes.Cylinder001_3.geometry}
          material={gltf.materials['default']}
        />
        <T.Mesh
          name="Cylinder001_4"
          geometry={gltf.nodes.Cylinder001_4.geometry}
          material={gltf.materials['Material.018']}
        />
        <T.Mesh
          name="Cylinder001_5"
          geometry={gltf.nodes.Cylinder001_5.geometry}
          material={gltf.materials['Material.015']}
        />
        <T.Mesh
          name="Cylinder001_6"
          geometry={gltf.nodes.Cylinder001_6.geometry}
          material={gltf.materials['Material.017']}
        />
      </T.Group>
      <T.Group
        name="Cylinder025"
        rotation={[Math.PI / 2, 0, 0]}
      >
        <T.Mesh
          name="Cylinder025_1"
          geometry={gltf.nodes.Cylinder025_1.geometry}
          material={gltf.materials['Material.073']}
        />
        <T.Mesh
          name="Cylinder025_2"
          geometry={gltf.nodes.Cylinder025_2.geometry}
          material={gltf.materials['Material.066']}
        />
        <T.Mesh
          name="Cylinder025_3"
          geometry={gltf.nodes.Cylinder025_3.geometry}
          material={gltf.materials['Material.061']}
        />
        <T.Mesh
          name="Cylinder025_4"
          geometry={gltf.nodes.Cylinder025_4.geometry}
          material={gltf.materials['Material.064']}
        />
        <T.Mesh
          name="Cylinder025_5"
          geometry={gltf.nodes.Cylinder025_5.geometry}
          material={gltf.materials['Material.062']}
        />
        <T.Mesh
          name="Cylinder025_6"
          geometry={gltf.nodes.Cylinder025_6.geometry}
          material={gltf.materials['Material.067']}
        />
        <T.Mesh
          name="Cylinder025_7"
          geometry={gltf.nodes.Cylinder025_7.geometry}
          material={gltf.materials['Material.063']}
        />
        <T.Mesh
          name="Cylinder025_8"
          geometry={gltf.nodes.Cylinder025_8.geometry}
          material={gltf.materials['Material.065']}
        />
        <T.Mesh
          name="Cylinder025_9"
          geometry={gltf.nodes.Cylinder025_9.geometry}
          material={gltf.materials['Material.069']}
        />
        <T.Mesh
          name="Cylinder025_10"
          geometry={gltf.nodes.Cylinder025_10.geometry}
          material={gltf.materials['Material.072']}
        />
        <T.Mesh
          name="Cylinder025_11"
          geometry={gltf.nodes.Cylinder025_11.geometry}
          material={gltf.materials['Material.068']}
        />
        <T.Mesh
          name="Cylinder025_12"
          geometry={gltf.nodes.Cylinder025_12.geometry}
          material={gltf.materials['Material.017']}
        />
        <T.Mesh
          name="Cylinder025_13"
          geometry={gltf.nodes.Cylinder025_13.geometry}
          material={gltf.materials['Material.071']}
        />
      </T.Group>
      <T.Group
        name="Cylinder008"
        position={[0, 0, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <T.Mesh
          name="Cylinder003"
          geometry={gltf.nodes.Cylinder003.geometry}
          material={gltf.materials['Material.001']}
        />
        <T.Mesh
          name="Cylinder003_1"
          geometry={gltf.nodes.Cylinder003_1.geometry}
          material={gltf.materials['Material.020']}
        />
        <T.Mesh
          name="Cylinder003_2"
          geometry={gltf.nodes.Cylinder003_2.geometry}
          material={gltf.materials['SVGMat.002']}
        />
        <T.Mesh
          name="Cylinder003_3"
          geometry={gltf.nodes.Cylinder003_3.geometry}
          material={gltf.materials['Material.019']}
        />
        <T.Mesh
          name="Cylinder003_4"
          geometry={gltf.nodes.Cylinder003_4.geometry}
          material={gltf.materials['Material.023']}
        />
        <T.Mesh
          name="Cylinder003_5"
          geometry={gltf.nodes.Cylinder003_5.geometry}
          material={gltf.materials['Material.025']}
        />
        <T.Mesh
          name="Cylinder003_6"
          geometry={gltf.nodes.Cylinder003_6.geometry}
          material={gltf.materials['Material.026']}
        />
        <T.Mesh
          name="Cylinder003_7"
          geometry={gltf.nodes.Cylinder003_7.geometry}
          material={gltf.materials['Material.022']}
        />
        <T.Mesh
          name="Cylinder003_8"
          geometry={gltf.nodes.Cylinder003_8.geometry}
          material={gltf.materials['Material.021']}
        />
        <T.Mesh
          name="Cylinder003_9"
          geometry={gltf.nodes.Cylinder003_9.geometry}
          material={gltf.materials['Material.031']}
        />
        <T.Mesh
          name="Cylinder003_10"
          geometry={gltf.nodes.Cylinder003_10.geometry}
          material={gltf.materials['Material.072']}
        />
        <T.Mesh
          name="Cylinder003_11"
          geometry={gltf.nodes.Cylinder003_11.geometry}
          material={gltf.materials['Material.028']}
        />
        <T.Mesh
          name="Cylinder003_12"
          geometry={gltf.nodes.Cylinder003_12.geometry}
          material={gltf.materials['Material.032']}
        />
        <T.Mesh
          name="Cylinder003_13"
          geometry={gltf.nodes.Cylinder003_13.geometry}
          material={gltf.materials['Material.030']}
        />
        <T.Mesh
          name="Cylinder003_14"
          geometry={gltf.nodes.Cylinder003_14.geometry}
          material={gltf.materials['Material.027']}
        />
        <T.Mesh
          name="Cylinder003_15"
          geometry={gltf.nodes.Cylinder003_15.geometry}
          material={gltf.materials['Material.024']}
        />
      </T.Group>
      <T.Group
        name="Cylinder029"
        rotation={[Math.PI / 2, 0, 0]}
      >
        <T.Mesh
          name="Cylinder007"
          geometry={gltf.nodes.Cylinder007.geometry}
          material={gltf.materials['Shiba inu Coin']}
        />
        <T.Mesh
          name="Cylinder007_1"
          geometry={gltf.nodes.Cylinder007_1.geometry}
          material={gltf.materials['Shiba logo 1']}
        />
        <T.Mesh
          name="Cylinder007_2"
          geometry={gltf.nodes.Cylinder007_2.geometry}
          material={gltf.materials['Shiba logo 4']}
        />
        <T.Mesh
          name="Cylinder007_3"
          geometry={gltf.nodes.Cylinder007_3.geometry}
          material={gltf.materials['Material.030']}
        />
        <T.Mesh
          name="Cylinder007_4"
          geometry={gltf.nodes.Cylinder007_4.geometry}
          material={gltf.materials['Material.072']}
        />
      </T.Group>
      <T.Group
        name="Cylinder017"
        rotation={[Math.PI / 2, 0, 0]}
      >
        <T.Mesh
          name="Cylinder002"
          geometry={gltf.nodes.Cylinder002.geometry}
          material={gltf.materials['Near Coin']}
        />
        <T.Mesh
          name="Cylinder002_1"
          geometry={gltf.nodes.Cylinder002_1.geometry}
          material={gltf.materials['Material.072']}
        />
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T>
