/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 coins.glb -d 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/coins.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.002, -0.002, 0.002]}>
        <mesh geometry={nodes.electrum_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.electrum_2.geometry} material={materials['SVGMat.006']} />
        <mesh geometry={nodes.electrum_3.geometry} material={materials['SVGMat.008']} />
      </group>
      <group position={[-0.001, -0.001, 0]}>
        <mesh geometry={nodes.doge_1.geometry} material={materials['Near Logo']} />
        <mesh geometry={nodes.doge_2.geometry} material={materials['Material.066']} />
        <mesh geometry={nodes.doge_3.geometry} material={materials['Material.061']} />
        <mesh geometry={nodes.doge_4.geometry} material={materials['Material.064']} />
        <mesh geometry={nodes.doge_5.geometry} material={materials['Material.062']} />
        <mesh geometry={nodes.doge_6.geometry} material={materials['Material.067']} />
        <mesh geometry={nodes.doge_7.geometry} material={materials['Material.063']} />
        <mesh geometry={nodes.doge_8.geometry} material={materials['Material.065']} />
        <mesh geometry={nodes.doge_9.geometry} material={materials['Material.069']} />
        <mesh geometry={nodes.doge_10.geometry} material={materials['Material.068']} />
        <mesh geometry={nodes.doge_11.geometry} material={materials['Material.070']} />
        <mesh geometry={nodes.doge_12.geometry} material={materials['Material.071']} />
        <mesh geometry={nodes.doge_13.geometry} material={materials['Material.073']} />
      </group>
      <group position={[-0.011, -0.005, 0.003]}>
        <mesh geometry={nodes.cat_1.geometry} material={materials['Material.020']} />
        <mesh geometry={nodes.cat_2.geometry} material={materials['SVGMat.012']} />
        <mesh geometry={nodes.cat_3.geometry} material={materials['Material.019']} />
        <mesh geometry={nodes.cat_4.geometry} material={materials['Material.023']} />
        <mesh geometry={nodes.cat_5.geometry} material={materials['Material.025']} />
        <mesh geometry={nodes.cat_6.geometry} material={materials['Material.026']} />
        <mesh geometry={nodes.cat_7.geometry} material={materials['Material.022']} />
        <mesh geometry={nodes.cat_8.geometry} material={materials['Material.021']} />
        <mesh geometry={nodes.cat_9.geometry} material={materials['Material.031']} />
        <mesh geometry={nodes.cat_10.geometry} material={materials['Near Logo']} />
        <mesh geometry={nodes.cat_11.geometry} material={materials['Material.028']} />
        <mesh geometry={nodes.cat_12.geometry} material={materials['Material.032']} />
        <mesh geometry={nodes.cat_13.geometry} material={materials['Material.030']} />
        <mesh geometry={nodes.cat_14.geometry} material={materials['Material.027']} />
        <mesh geometry={nodes.cat_15.geometry} material={materials['Material.024']} />
        <mesh geometry={nodes.cat_16.geometry} material={materials['Material.007']} />
      </group>
      <group position={[-0.002, 0.013, 0.004]}>
        <mesh geometry={nodes.shiba_1.geometry} material={materials['Shiba logo 1']} />
        <mesh geometry={nodes.shiba_2.geometry} material={materials['Shiba logo 4']} />
        <mesh geometry={nodes.shiba_3.geometry} material={materials['Material.030']} />
        <mesh geometry={nodes.shiba_4.geometry} material={materials['Near Logo']} />
        <mesh geometry={nodes.shiba_5.geometry} material={materials['Shiba inu Coin']} />
      </group>
      <group position={[-0.01, -0.005, 0.003]}>
        <mesh geometry={nodes.pepe_1.geometry} material={materials['SVGMat.012']} />
        <mesh geometry={nodes.pepe_2.geometry} material={materials.SVGMat} />
        <mesh geometry={nodes.pepe_3.geometry} material={materials['SVGMat.001']} />
        <mesh geometry={nodes.pepe_4.geometry} material={materials['Pepe Coin']} />
      </group>
      <group position={[0.003, -0.003, 0]}>
        <mesh geometry={nodes.pinguin001.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.pinguin001_1.geometry} material={materials['default.003']} />
        <mesh geometry={nodes.pinguin001_2.geometry} material={materials['Material.033']} />
        <mesh geometry={nodes.pinguin001_3.geometry} material={materials['Material.034']} />
        <mesh geometry={nodes.pinguin001_4.geometry} material={materials['Material.035']} />
        <mesh geometry={nodes.pinguin001_5.geometry} material={materials['Material.070']} />
      </group>
      <mesh geometry={nodes.near001.geometry} material={materials['Near Coin']} rotation={[0, 0, -Math.PI]} scale={[1.021, 1.021, 1.028]} />
      <mesh geometry={nodes.Curve001.geometry} material={materials['SVGMat.007']} position={[-0.023, -0.09, 0.002]} rotation={[Math.PI / 2, 0, 0]} scale={38.939} />
    </group>
  )
}

useGLTF.preload('/coins.glb')
